name = "DiagonalizeHamiltonian"
uuid = "6ee7953c-facd-4073-bf73-d29b8b119bcc"
version = "0.1.0"
authors = ["souta "]

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Lattice2D = "e8031020-b7ff-4f1d-bee4-f79aea4cf140"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Arpack = "0.5.4"
Lattice2D = "0.1.2"
LinearAlgebra = "1.12.0"
Measures = "0.3.3"
Plots = "1.41.2"
Random = "1.11.0"
Reexport = "1.2.2"
SparseArrays = "1.12.0"
Statistics = "1.11.1"
Test = "1.11.0"
